### ISSUE TITLE
Details for appjail0 in README needed

### ISSUE THREAD

**Issue by paul-hammant** [AppJail-makejails/debian#2]
"In the above example appjail0 is a loopback interface, so it must first exist before creating the jail."

What;s the command to create loopback interface appjail0?  The README assumes the reader knows how to do that, but perhaps shouldn't

**Comment by paul-hammant** [comment]
The alpine-linux repo in this org has a line "Tip: Read [Alias & Virtual Networks](https://appjail.readthedocs.io/en/latest/networking/virtual-networks/alias-and-virtual-networks/) to see how to create the appjail0 interface."

It is unclear whether that line as is, should be in more of the READMEs of the AppJail-makejails org.

**Comment by DtxdF** [comment]
Related: https://github.com/AppJail-makejails/ubuntu/issues/1#issuecomment-2002536275

**Comment by DtxdF** [comment]
This issue has been closed due to inactivity. You can reopen it if you wish.
